### ISSUE TITLE
How do i add a Directory?

### ISSUE THREAD

**Issue by Erickson400** [kdomanski/iso9660#10]
I want to add 2 files and one directory, is that not possible?

**Comment by kdomanski** [comment]
Hi @Erickson400 there isn't any convenience function for this now, but you can add a directory by just adding its contents file by file at the correct paths.

**Comment by kdomanski** [comment]
New version has a `AddLocalDirectory` helper function.

**Comment by freakytoad1** [comment]
Can an empty directory be added?

I need to create a few folders in the ISO that are intentionally empty. Looks like they are skipped over in AddLocalDirectory if it is empty.
