### ISSUE TITLE
Proposal: Please start using Semantic Versioning

### ISSUE THREAD

**Issue by KateGo520** [kdomanski/iso9660#6]
I found that this project already [supports Go modules](https://github.com/kdomanski/iso9660/blob/master/go.mod). But sadly, the [tags](https://github.com/kdomanski/iso9660/tags) doesn't follow [Semantic Versioning](https://semver.org), which means that all tags of this project will be ignored by Go modules and replaced by pseudo-versions, go get acts weirdly when tags are not in that form. It would be great to have the tagged release be named in the format vX.X.X format so that go mod can read it. 
```
$go get github.com/kdomanski/iso9660@v0.2
go get github.com/kdomanski/iso9660@v0.2: no matching versions for query "v0.2"
$go get github.com/kdomanski/iso9660
go: downloading github.com/kdomanski/iso9660 v0.0.0-20200713230927-fa56c38dc741
go: github.com/kdomanski/iso9660 upgrade => v0.0.0-20200713230927-fa56c38dc741
```
Else the mod file shows something like `github.com/kdomanski/iso9660 v0.0.0-20200713230927-fa56c38dc741` which is not very readable and difficult to upgrade. It’s hard to verify which version is in use. This is not conducive to version control.

So, I propose this project to follow Semantic Versioning in future versions. For example, `v1.0.1`, `v2.0.0`, `v3.1.0-alpha`, `v3.1.0-beta.2`etc, so that other project can use tag in go.mod.

**Comment by KateGo520** [comment]
@kdomanski  @mat007  Could you help me review this issue? Thx :p

**Comment by kdomanski** [comment]
Hi @KateGo520 , I retagged `v0.2` as `v0.2.0`. On my machine `go get` seems to work now. Will that (and sticking to semver in the future) be sufficient?

**Comment by KateGo520** [comment]
@kdomanski It works now! Thank you for your contribution!
> $go get github.com/kdomanski/iso9660
> go: downloading github.com/kdomanski/iso9660 v0.2.0
> go: github.com/kdomanski/iso9660 upgrade => v0.2.0
