### ISSUE TITLE
Feature Request: Joliet and Rock Ridge extensions supporting.

### ISSUE THREAD

**Issue by vdmvoro** [kdomanski/iso9660#7]
Good day 
Hope you are doing well.

For now: Joliet and Rock Ridge extensions are not supported.
Do you plan to write additional methods for supporting them?

**Comment by davidnewhall** [comment]
In case it helps... I found 1 [old library](https://github.com/dgodd/iso9660/tree/master) that has Rock Ridge support, and 1 that [supports UDF](https://github.com/mogaika/udf), but I found none that support Joliet.

**Comment by davidnewhall** [comment]
Thanks for everything so far, Kamil. Much appreciated!

**Comment by kdomanski** [comment]
Converting this into separate tracking issues:
- https://github.com/kdomanski/iso9660/issues/37
- https://github.com/kdomanski/iso9660/issues/38
- https://github.com/kdomanski/iso9660/issues/39
- https://github.com/kdomanski/iso9660/issues/40
